name: schedule

# on:
#   schedule:
#     - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: \[AWS\] Fetch latest instance & price info
        run: |
          SAVE_PATH=./store/aws/`date +%Y-%m-%dF`
          mkdir -p $SAVE_PATH
          cat ./.github/www/aws | xargs curl > $SAVE_PATH

      - name: Push to the remote repo
        run: |
          git config --local user.email "bot@bytebase.com"
          git config --local user.name "bot"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git add .
          git commit -m "update by github action"
          git push -f
