name: schedule

# for now we trigger this event manually
on: workflow_dispatch
#   schedule:
#     - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Fetch latest pricing data
        run: |
          export API_KEY_GCP=${{ secrets.API_KEY_GCP }}
          go run seed/main.go

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update report
          author: GitHub <noreply@github.com>
          branch: update-pricing-data
          delete-branch: true
          title: "Update pricing data"
          body: |
            Update pricing data.
          labels: |
            data update
            automated
          reviewers: Megrax
          draft: false
